# Thư mục gốc của project
root = "."

# Thư mục tạm (air dùng để build lại)
tmp_dir = "tmp"

# Chạy đúng file main.go trong thư mục con
[build]
  cmd = "go run cmd/server/main.go"
  bin = "tmp/main.exe"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "node_modules"]
  delay = 1000  # milliseconds
  kill_delay = 1000

[log]
  time = true
